name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List file
        working-directory: .
        run: ls -la
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            **/requirement.txt
            **/data/*
            **/logs/*
      - name: Install dependencies
        run: pip install -r requirement.txt
      - name: Crawling data
        run: python main.py
      # - name: Commit change
      #   run:
